name: test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          sudo ifconfig
          sudo route -n
          curl -vv --ipv6 "[2607:f8b0:4002:c03::93]:80"
          ping ipv6.google.com
